services:
  whitebox:
    image: rxyvea/whitebox:latest
    container_name: whitebox
    restart: unless-stopped
    ports:
      - 9116:9116
    command:
      - '--config.file=/etc/whitebox/whitebox.yml'
    volumes:
      - ./whitebox.yml:/etc/whitebox/whitebox.yml
