services:
  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    restart: unless-stopped
    ports:
      - 9115:9115
    command:
      - '--config.file=/etc/blackbox/blackbox.yml'
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml

  whitebox:
    container_name: whitebox
    build: ..
    restart: unless-stopped
    ports:
      - 9116:9116

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: 65534:65534
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.wal-compression'
      - '--web.enable-lifecycle'
    depends_on:
      - blackbox
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./whitebox-sd-config.yml:/etc/prometheus/whitebox-sd-config.yml:ro
      - prometheus_data:/prometheus
    deploy:
      resources:
        limits:
          memory: 2G

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: 472:472
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=${GF_DOMAIN:-localhost}
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  prometheus_data:
  grafana_data:
